document.getElementById('banner');
document.getElementById('paraChange');
document.getElementById('headerChange');

function changeText1(){
document.getElementById("headerChange").innerHTML = "Magna Ipsum Dolor";
document.getElementById("paraChange").innerHTML = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra mauris in aliquam sem. Tempor commodo ullamcorper a lacus vestibulum sed. Eget aliquet nibh praesent tristique magna sit. Elit eget gravida cum sociis natoque penatibus et. In hac habitasse platea dictumst quisque sagittis purus sit. Eget aliquet nibh praesent tristique. A pellentesque sit amet porttitor eget dolor morbi non arcu. Velit dignissim sodales ut eu sem. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. At in tellus integer feugiat scelerisque varius morbi enim. Dignissim suspendisse in est ante in. A diam maecenas sed enim ut sem viverra.Quis lectus nulla at volutpat diam ut venenatis tellus. Proin sagittis nisl rhoncus mattis rhoncus urna. Orci porta non pulvinar neque laoreet suspendisse interdum. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Erat velit scelerisque in dictum non consectetur a erat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Commodo nulla facilisi nullam vehicula. Diam donec adipiscing tristique risus nec feugiat in fermentum posuere. Justo nec ultrices dui sapien eget mi. Dolor magna eget est lorem ipsum dolor sit amet consectetur. Ut eu sem integer vitae justo eget magna. Risus ultricies tristique nulla aliquet enim tortor. Nunc faucibus a pellentesque sit amet. Vel pretium lectus quam id leo in. Tellus molestie nunc non blandit massa enim nec dui nunc. Ut venenatis tellus in metus vulputate eu scelerisque. Molestie nunc non blandit massa enim nec dui nunc. Rutrum quisque non tellus orci ac auctor augue. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in dictum. In arcu cursus euismod quis viverra nibh cras pulvinar mattis. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

banner.style.background = '#333333';
paraChange.style.color = '#EAEAEA';
//headerChange.style.fontSize = "80px";
}

function changeText2(){
document.getElementById("headerChange").innerHTML = "Lorem Lorem Lorem";
document.getElementById("paraChange").innerHTML = "Diam volutpat commodo sed egestas egestas fringilla phasellus. Congue quisque egestas diam in arcu cursus. Nisl pretium fusce id velit ut tortor pretium viverra suspendisse. Ornare quam viverra orci sagittis eu volutpat odio. Volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Vitae semper quis lectus nulla at. Etiam erat velit scelerisque in dictum non consectetur a. Diam vel quam elementum pulvinar etiam non quam lacus. Ultricies integer quis auctor elit. In pellentesque massa placerat duis ultricies lacus sed. Massa sed elementum tempus egestas sed sed risus pretium. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Volutpat lacus laoreet non curabitur gravida arcu. Risus in hendrerit gravida rutrum quisque. Eu volutpat odio facilisis mauris. Adipiscing elit duis tristique sollicitudin. Natoque penatibus et magnis dis parturient montes. Nibh ipsum consequat nisl vel pretium lectus quam. Cras adipiscing enim eu turpis egestas pretium aenean pharetra.Faucibus et molestie ac feugiat sed lectus vestibulum. Nisi quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Placerat duis ultricies lacus sed turpis tincidunt id aliquet risus. Enim nulla aliquet porttitor lacus luctus accumsan. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Pellentesque habitant morbi tristique senectus et netus. Turpis egestas pretium aenean pharetra magna ac placerat. Morbi non arcu risus quis varius quam quisque id diam. Velit scelerisque in dictum non consectetur a erat. Blandit cursus risus at ultrices mi. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Elit ut aliquam purus sit amet luctus venenatis lectus. Aenean et tortor at risus viverra adipiscing at. Lacus laoreet non curabitur gravida arcu. Ullamcorper a lacus vestibulum sed arcu non odio euismod lacinia. Cursus mattis molestie a iaculis. Ut tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Elementum tempus egestas sed sed risus pretium quam. In eu mi bibendum neque.";

 banner.style.background = '#1CA5FF';
 paraChange.style.color = '#333333';
 //headerChange.style.fontSize = "80px";
}
function changeText3(){
document.getElementById("headerChange").innerHTML = "Ipsum Ipsum Ipsum";
document.getElementById("paraChange").innerHTML = "Diam volutpat commodo sed egestas egestas fringilla phasellus. Congue quisque egestas diam in arcu cursus. Nisl pretium fusce id velit ut tortor pretium viverra suspendisse. Ornare quam viverra orci sagittis eu volutpat odio. Volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Vitae semper quis lectus nulla at. Etiam erat velit scelerisque in dictum non consectetur a. Diam vel quam elementum pulvinar etiam non quam lacus. Ultricies integer quis auctor elit. In pellentesque massa placerat duis ultricies lacus sed. Massa sed elementum tempus egestas sed sed risus pretium. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Volutpat lacus laoreet non curabitur gravida arcu. Risus in hendrerit gravida rutrum quisque. Eu volutpat odio facilisis mauris. Adipiscing elit duis tristique sollicitudin. Natoque penatibus et magnis dis parturient montes. Nibh ipsum consequat nisl vel pretium lectus quam. Cras adipiscing enim eu turpis egestas pretium aenean pharetra.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae suscipit tellus mauris a diam maecenas. Senectus et netus et malesuada fames ac. In nibh mauris cursus mattis molestie a. Hac habitasse platea dictumst quisque sagittis purus sit amet volutpat. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Tellus id interdum velit laoreet id. Dolor purus non enim praesent elementum. Laoreet sit amet cursus sit amet dictum sit. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Sit amet nulla facilisi morbi tempus. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Felis donec et odio pellentesque diam volutpat. Urna neque viverra justo nec ultrices dui. Rhoncus mattis rhoncus urna neque viverra justo. At varius vel pharetra vel turpis nunc eget lorem dolor. Viverra suspendisse potenti nullam ac. Maecenas ultricies mi eget mauris pharetra et ultrices";

 banner.style.background = '#FF8631';
 paraChange.style.color = '#333333';
 //headerChange.style.fontSize = "80px";
}
function changeText4(){
document.getElementById("headerChange").innerHTML = "Dolor Dolor Dolor";
document.getElementById("paraChange").innerHTML = "Diam volutpat commodo sed egestas egestas fringilla phasellus. Congue quisque egestas diam in arcu cursus. Nisl pretium fusce id velit ut tortor pretium viverra suspendisse. Ornare quam viverra orci sagittis eu volutpat odio. Volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Vitae semper quis lectus nulla at. Etiam erat velit scelerisque in dictum non consectetur a. Diam vel quam elementum pulvinar etiam non quam lacus. Ultricies integer quis auctor elit. In pellentesque massa placerat duis ultricies lacus sed. Massa sed elementum tempus egestas sed sed risus pretium. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Volutpat lacus laoreet non curabitur gravida arcu. Risus in hendrerit gravida rutrum quisque. Eu volutpat odio facilisis mauris. Adipiscing elit duis tristique sollicitudin. Natoque penatibus et magnis dis parturient montes. Nibh ipsum consequat nisl vel pretium lectus quam. Cras adipiscing enim eu turpis egestas pretium aenean pharetra.Pellentesque elit eget gravida cum sociis natoque penatibus. Ultrices eros in cursus turpis massa tincidunt dui ut ornare. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Ac tortor dignissim convallis aenean et tortor. Sodales ut eu sem integer. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices vitae auctor eu augue ut. Neque gravida in fermentum et. Sit amet mattis vulputate enim nulla aliquet porttitor. Amet justo donec enim diam vulputate ut pharetra. Diam ut venenatis tellus in. Porta lorem mollis aliquam ut. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Et netus et malesuada fames ac turpis egestas integer.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

 banner.style.background = ' #27B44B';
 paraChange.style.color = '#333333';
 //headerChange.style.fontSize = "80px";
}
function changeText5(){
document.getElementById("headerChange").innerHTML = "Magna Magna Magna";
document.getElementById("paraChange").innerHTML = "Diam volutpat commodo sed egestas egestas fringilla phasellus. Congue quisque egestas diam in arcu cursus. Nisl pretium fusce id velit ut tortor pretium viverra suspendisse. Ornare quam viverra orci sagittis eu volutpat odio. Volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Vitae semper quis lectus nulla at. Etiam erat velit scelerisque in dictum non consectetur a. Diam vel quam elementum pulvinar etiam non quam lacus. Ultricies integer quis auctor elit. In pellentesque massa placerat duis ultricies lacus sed. Massa sed elementum tempus egestas sed sed risus pretium. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Volutpat lacus laoreet non curabitur gravida arcu. Risus in hendrerit gravida rutrum quisque. Eu volutpat odio facilisis mauris. Adipiscing elit duis tristique sollicitudin. Natoque penatibus et magnis dis parturient montes. Nibh ipsum consequat nisl vel pretium lectus quam. Cras adipiscing enim eu turpis egestas pretium aenean pharetra.Fringilla phasellus faucibus scelerisque eleifend donec pretium. Mauris nunc congue nisi vitae suscipit tellus mauris. Sed cras ornare arcu dui. Id faucibus nisl tincidunt eget nullam non nisi est. At consectetur lorem donec massa. Neque sodales ut etiam sit. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est velit. Amet commodo nulla facilisi nullam vehicula ipsum. Duis at consectetur lorem donec massa sapien faucibus. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Eget arcu dictum varius duis at consectetur lorem donec. Diam sit amet nisl suscipit. Vitae sapien pellentesque habitant morbi tristique senectus. Vel facilisis volutpat est velit egestas dui id ornare.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

 banner.style.background = '#E45845';
 paraChange.style.color = '#333333';
 //headerChange.style.fontSize = "80px";
}
function changeText6(){
document.getElementById("headerChange").innerHTML = "Etiam Etiam Etiam";
document.getElementById("paraChange").innerHTML = "Diam volutpat commodo sed egestas egestas fringilla phasellus. Congue quisque egestas diam in arcu cursus. Nisl pretium fusce id velit ut tortor pretium viverra suspendisse. Ornare quam viverra orci sagittis eu volutpat odio. Volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Vitae semper quis lectus nulla at. Etiam erat velit scelerisque in dictum non consectetur a. Diam vel quam elementum pulvinar etiam non quam lacus. Ultricies integer quis auctor elit. In pellentesque massa placerat duis ultricies lacus sed. Massa sed elementum tempus egestas sed sed risus pretium. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Volutpat lacus laoreet non curabitur gravida arcu. Risus in hendrerit gravida rutrum quisque. Eu volutpat odio facilisis mauris. Adipiscing elit duis tristique sollicitudin. Natoque penatibus et magnis dis parturient montes. Nibh ipsum consequat nisl vel pretium lectus quam. Cras adipiscing enim eu turpis egestas pretium aenean pharetra.Pellentesque elit eget gravida cum sociis natoque penatibus. Ultrices eros in cursus turpis massa tincidunt dui ut ornare. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Ac tortor dignissim convallis aenean et tortor. Sodales ut eu sem integer. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Viverra aliquet eget sit amet tellus cras adipiscing enim. Ultrices vitae auctor eu augue ut. Neque gravida in fermentum et. Sit amet mattis vulputate enim nulla aliquet porttitor. Amet justo donec enim diam vulputate ut pharetra. Diam ut venenatis tellus in. Porta lorem mollis aliquam ut. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Et netus et malesuada fames ac turpis egestas integer.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

 banner.style.background = '#BC5BE6';
 paraChange.style.color = '#333333';
//headerChange.style.fontSize = "80px";
}
function changeText7(){
document.getElementById("headerChange").innerHTML = "Ornare Ornare Ornare";
document.getElementById("paraChange").innerHTML = "Diam volutpat commodo sed egestas egestas fringilla phasellus. Congue quisque egestas diam in arcu cursus. Nisl pretium fusce id velit ut tortor pretium viverra suspendisse. Ornare quam viverra orci sagittis eu volutpat odio. Volutpat consequat mauris nunc congue nisi vitae. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Vitae semper quis lectus nulla at. Etiam erat velit scelerisque in dictum non consectetur a. Diam vel quam elementum pulvinar etiam non quam lacus. Ultricies integer quis auctor elit. In pellentesque massa placerat duis ultricies lacus sed. Massa sed elementum tempus egestas sed sed risus pretium. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Volutpat lacus laoreet non curabitur gravida arcu. Risus in hendrerit gravida rutrum quisque. Eu volutpat odio facilisis mauris. Adipiscing elit duis tristique sollicitudin. Natoque penatibus et magnis dis parturient montes. Nibh ipsum consequat nisl vel pretium lectus quam. Cras adipiscing enim eu turpis egestas pretium aenean pharetra.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae suscipit tellus mauris a diam maecenas. Senectus et netus et malesuada fames ac. In nibh mauris cursus mattis molestie a. Hac habitasse platea dictumst quisque sagittis purus sit amet volutpat. Bibendum est ultricies integer quis auctor elit sed vulputate mi. Tellus id interdum velit laoreet id. Dolor purus non enim praesent elementum. Laoreet sit amet cursus sit amet dictum sit. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Sit amet nulla facilisi morbi tempus. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Felis donec et odio pellentesque diam volutpat. Urna neque viverra justo nec ultrices dui. Rhoncus mattis rhoncus urna neque viverra justo. At varius vel pharetra vel turpis nunc eget lorem dolor. Viverra suspendisse potenti nullam ac. Maecenas ultricies mi eget mauris pharetra et ultrices.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

 banner.style.background = '#333333';
 paraChange.style.color = '#EAEAEA ';
 //headerChange.style.fontSize = "70px";
}
